In [1]:
#Imports
#numpy, pandas, scipy,math, matplotlibrary
import numpy as np
import pandas as pd
import scipy
from math import sqrt
import matplotlib.pyplot as plt

In [25]:
#Model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [2]:
#Cross Validation
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [3]:
# estimators
from sklearn.ensemble import RandomForestRegressor 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

In [4]:
#data
concrete = pd.read_excel('Concrete_Data.xls', header =1)
# Características de las variables
concrete.head()

X1     X2   X3     X4   X5      X6     X7   X8         Y1
0  540.0    0.0  0.0  162.0  2.5  1040.0  676.0   28  79.986111
1  540.0    0.0  0.0  162.0  2.5  1055.0  676.0   28  61.887366
2  332.5  142.5  0.0  228.0  0.0   932.0  594.0  270  40.269535
3  332.5  142.5  0.0  228.0  0.0   932.0  594.0  365  41.052780
4  198.6  132.4  0.0  192.0  0.0   978.4  825.5  360  44.296075

In [6]:
concrete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
X1    1030 non-null float64
X2    1030 non-null float64
X3    1030 non-null float64
X4    1030 non-null float64
X5    1030 non-null float64
X6    1030 non-null float64
X7    1030 non-null float64
X8    1030 non-null int64
Y1    1030 non-null float64
dtypes: float64(8), int64(1)
memory usage: 72.5 KB


In [10]:
#features
features = concrete.iloc[:,0:8]
print('Summary of feature sample')
features.head()

Summary of feature sample


X1     X2   X3     X4   X5      X6     X7   X8
0  540.0    0.0  0.0  162.0  2.5  1040.0  676.0   28
1  540.0    0.0  0.0  162.0  2.5  1055.0  676.0   28
2  332.5  142.5  0.0  228.0  0.0   932.0  594.0  270
3  332.5  142.5  0.0  228.0  0.0   932.0  594.0  365
4  198.6  132.4  0.0  192.0  0.0   978.4  825.5  360

In [11]:
#dependent variable
depVar = concrete['Y1']

In [12]:
#Training Set (Feature Space: X Training)
X_train = (features[: 1000])
X_train.head()

X1     X2   X3     X4   X5      X6     X7   X8
0  540.0    0.0  0.0  162.0  2.5  1040.0  676.0   28
1  540.0    0.0  0.0  162.0  2.5  1055.0  676.0   28
2  332.5  142.5  0.0  228.0  0.0   932.0  594.0  270
3  332.5  142.5  0.0  228.0  0.0   932.0  594.0  365
4  198.6  132.4  0.0  192.0  0.0   978.4  825.5  360

In [13]:
#Dependent Variable Training Set (y Training)
y_train = depVar[: 1000]
y_train_count = len(y_train.index)
print('The number of observations in the Y training set are:',str(y_train_count))
y_train.head()

The number of observations in the Y training set are: 1000


0    79.986111
1    61.887366
2    40.269535
3    41.052780
4    44.296075
Name: Y1, dtype: float64

In [14]:
#Testing Set (X Testing)
X_test = features[-100:]
X_test_count = len(X_test.index)
print('The number of observations in the feature testing set is:',str(X_test_count))
print(X_test.head())

The number of observations in the feature testing set is: 100
        X1     X2     X3     X4   X5      X6     X7  X8
930  159.0  209.0  161.0  201.0  7.0   848.0  669.0  28
931  144.0   15.0  195.0  176.0  6.0  1021.0  709.0  28
932  154.0  174.0  185.0  228.0  7.0   845.0  612.0  28
933  167.0  187.0  195.0  185.0  7.0   898.0  636.0  28
934  184.0   86.0  190.0  213.0  6.0   923.0  623.0  28


In [15]:
#Ground Truth (y_test) 
y_test = depVar[-100:]
y_test_count = len(y_test.index)
print('The number of observations in the Y training set are:',str(y_test_count))
y_test.head()

The number of observations in the Y training set are: 100


930    30.881630
931    15.340841
932    24.338503
933    23.890343
934    22.931972
Name: Y1, dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train)
X_train.shape, X_test.shape

((750, 8), (250, 8))

In [17]:
#Models
modelSVR = SVR()
modelRF = RandomForestRegressor()
modelLR = LinearRegression()

In [18]:
modelRF.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [19]:
#Model Fitting
modelRF.fit(X_train,y_train)
print(cross_val_score(modelRF, X_train, y_train))
modelRF.score(X_train,y_train)

[0.86974248 0.86458298 0.82971368]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


0.9802941725364492

In [20]:
modelSVR.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
modelSVR.fit(X_train,y_train)
print(cross_val_score(modelSVR, X_train, y_train)) 
modelSVR.score(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma

[ 0.01174493  0.01886608 -0.02007447]


0.10991081618617615

In [22]:
modelLR.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [23]:
modelLR.fit(X_train,y_train)
print(cross_val_score(modelLR, X_train, y_train)) 
modelLR.score(X_train,y_train)

[0.62257135 0.57520796 0.62716818]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


0.625175364557943

In [26]:
#MOdel for predictions RF, highest value 0.98
#Make Predictions
predictions = modelRF.predict(X_test)
predRsquared = r2_score(y_test,predictions)
rmse = sqrt(mean_squared_error(y_test, predictions))
print('R Squared: %.3f' % predRsquared)
print('RMSE: %.3f' % rmse)

R Squared: 0.879
RMSE: 5.677
